/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author attry
 */
public class PanelPrincipalTutor extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipalTutor
     */
    public PanelPrincipalTutor() {
        initComponents();
        
        RegistrarEstudiantes registrarEstudiantes = new RegistrarEstudiantes();
        registrarEstudiantes.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(registrarEstudiantes, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
        
        this.getContentPane().setBackground(Color.decode("#1b1d31"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        componentMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        RegistrarEstudiante = new javax.swing.JLabel();
        ConsultarCitasTutor = new javax.swing.JLabel();
        EstablecerHorarios = new javax.swing.JLabel();
        ModificarEstudiante = new javax.swing.JLabel();
        ModificarCitasTutor = new javax.swing.JLabel();
        ModificarCitas2 = new javax.swing.JLabel();
        GenerarReportes = new javax.swing.JLabel();
        ConsultarEstudiantes = new javax.swing.JLabel();
        RegistrarCalificacion = new javax.swing.JLabel();
        contentDinamyc = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        componentMenu.setBackground(new java.awt.Color(36, 37, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE DE USUARIO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Online");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\attry\\OneDrive\\Documentos\\NetBeansProjects\\GestionSustentacionesLM\\src\\main\\java\\img\\user.png")); // NOI18N

        RegistrarEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegistrarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEstudiante.setText("Registrar Estudiantes");
        RegistrarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarEstudianteMouseClicked(evt);
            }
        });

        ConsultarCitasTutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultarCitasTutor.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarCitasTutor.setText("Consultar Citas");
        ConsultarCitasTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarCitasTutorMouseClicked(evt);
            }
        });

        EstablecerHorarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EstablecerHorarios.setForeground(new java.awt.Color(255, 255, 255));
        EstablecerHorarios.setText("Establecer Horarios");
        EstablecerHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstablecerHorariosMouseClicked(evt);
            }
        });

        ModificarEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModificarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        ModificarEstudiante.setText("Modificar Estudiantes");
        ModificarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarEstudianteMouseClicked(evt);
            }
        });

        ModificarCitasTutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModificarCitasTutor.setForeground(new java.awt.Color(255, 255, 255));
        ModificarCitasTutor.setText("Modificar Citas");
        ModificarCitasTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarCitasTutorMouseClicked(evt);
            }
        });

        ModificarCitas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModificarCitas2.setForeground(new java.awt.Color(255, 255, 255));
        ModificarCitas2.setText("Cerrar Sesion");

        GenerarReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenerarReportes.setForeground(new java.awt.Color(255, 255, 255));
        GenerarReportes.setText("Generar Reporte");

        ConsultarEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultarEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        ConsultarEstudiantes.setText("Consultar Estudiantes");
        ConsultarEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarEstudiantesMouseClicked(evt);
            }
        });

        RegistrarCalificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegistrarCalificacion.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCalificacion.setText("Registrar Calificaciones");
        RegistrarCalificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarCalificacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout componentMenuLayout = new javax.swing.GroupLayout(componentMenu);
        componentMenu.setLayout(componentMenuLayout);
        componentMenuLayout.setHorizontalGroup(
            componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentMenuLayout.createSequentialGroup()
                .addGroup(componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(componentMenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistrarCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addComponent(GenerarReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RegistrarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsultarCitasTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addGroup(componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModificarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EstablecerHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModificarCitasTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(componentMenuLayout.createSequentialGroup()
                                .addComponent(ModificarCitas2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(ConsultarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        componentMenuLayout.setVerticalGroup(
            componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(componentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(componentMenuLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistrarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConsultarEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistrarCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(EstablecerHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConsultarCitasTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModificarCitasTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenerarReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ModificarCitas2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentDinamyc.setBackground(new java.awt.Color(27, 29, 49));

        javax.swing.GroupLayout contentDinamycLayout = new javax.swing.GroupLayout(contentDinamyc);
        contentDinamyc.setLayout(contentDinamycLayout);
        contentDinamycLayout.setHorizontalGroup(
            contentDinamycLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        contentDinamycLayout.setVerticalGroup(
            contentDinamycLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(componentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(contentDinamyc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentDinamyc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(componentMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarEstudianteMouseClicked
        // TODO add your handling code here:
        
        RegistrarEstudiantes registrarEstudiantes = new RegistrarEstudiantes();
        registrarEstudiantes.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(registrarEstudiantes, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
    }//GEN-LAST:event_RegistrarEstudianteMouseClicked

    private void RegistrarCalificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarCalificacionMouseClicked
        // TODO add your handling code here:
        RegistrarCalificaciones registrarCalificaciones= new RegistrarCalificaciones();
        registrarCalificaciones.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(registrarCalificaciones, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
    }//GEN-LAST:event_RegistrarCalificacionMouseClicked

    private void ConsultarCitasTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarCitasTutorMouseClicked
        // TODO add your handling code here:
        
        ConsultarCitasTutor consultarCitasTutor = new ConsultarCitasTutor();
        consultarCitasTutor.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(consultarCitasTutor, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
    }//GEN-LAST:event_ConsultarCitasTutorMouseClicked

    private void ModificarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarEstudianteMouseClicked
        // TODO add your handling code here:
        
        ModificarEstudiantes modificarEstudiantes = new ModificarEstudiantes();
        modificarEstudiantes.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(modificarEstudiantes, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
    }//GEN-LAST:event_ModificarEstudianteMouseClicked

    private void EstablecerHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstablecerHorariosMouseClicked
        // TODO add your handling code here:
        
        EstablecerHorarios establecerHorarios = new EstablecerHorarios();
        establecerHorarios.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(establecerHorarios, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
        
        
    }//GEN-LAST:event_EstablecerHorariosMouseClicked

    private void ModificarCitasTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarCitasTutorMouseClicked
        // TODO add your handling code here:
        
        ModificarCitas modificarCitas = new ModificarCitas();
        modificarCitas.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(modificarCitas, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
    }//GEN-LAST:event_ModificarCitasTutorMouseClicked

    private void ConsultarEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarEstudiantesMouseClicked
        // TODO add your handling code here:
        
        ConsultarEstudiantes consultarEstudiantes = new ConsultarEstudiantes();
        consultarEstudiantes.setSize(550,589);
       
        contentDinamyc.setLocation(0, 0);
        contentDinamyc.removeAll();
        
        contentDinamyc.add(consultarEstudiantes, BorderLayout.CENTER);
        contentDinamyc.revalidate();        
        contentDinamyc.repaint();
        
    }//GEN-LAST:event_ConsultarEstudiantesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipalTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipalTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConsultarCitasTutor;
    private javax.swing.JLabel ConsultarEstudiantes;
    private javax.swing.JLabel EstablecerHorarios;
    private javax.swing.JLabel GenerarReportes;
    private javax.swing.JLabel ModificarCitas2;
    private javax.swing.JLabel ModificarCitasTutor;
    private javax.swing.JLabel ModificarEstudiante;
    private javax.swing.JLabel RegistrarCalificacion;
    private javax.swing.JLabel RegistrarEstudiante;
    private javax.swing.JPanel componentMenu;
    private javax.swing.JPanel contentDinamyc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
